### ISSUE TITLE
Use <audio> element 

### ISSUE THREAD

**Issue by ghost** [01000001-01101011/audio-player#2]
Consider using the HTML `<audio>` element in order to give the user more control over audio playback. 

### Pros:
- Can rewind/forward media
- Allows audio looping
- Sound control
- Better browser compatibility

### Cons:
- More JavaScript :)

Feel free to assign this issue to me if you approve of the idea.

**Comment by ahs3n** [comment]
Thanks for the suggestion!  It's probably a good idea but I wanted to keep the application as simple as possible (no audio control), and stored in a single html file.  I do appreciate the help, but I don't think I want to make this change.
